#job
apiVersion: batch/v1
kind: Job
metadata:
  name: user-api-migration
spec:
  template:
    spec:
      hostNetwork: true  # ADD THIS LINE
      nodeSelector:
        kubernetes.io/hostname: kubernetes  # ADD THIS LINE
      containers:
        - name: migrate
          image: mrkendono/userservice:latest
          command: ["sh", "-c"]
          args:
            - sleep 10 && flask db init && flask db migrate && flask db upgrade
          env:
            - name: DB_HOST
              value: "127.0.0.1"  # CHANGE FROM user-db TO 127.0.0.1
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: user
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: user-db-secret
                  key: MYSQL_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-db-secret
                  key: MYSQL_PASSWORD
      restartPolicy: Never
  backoffLimit: 3