apiVersion: batch/v1
kind: Job
metadata:
  name: user-api-migration
spec:
  template:
    spec:
      containers:
        - name: migrate
          image: mrkendono/frontend:latest
          command: ["sh", "-c"]
          args:
            - flask db init && flask db migrate && flask db upgrade
          env:
            - name: DB_HOST
              value: user-db
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: user
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: user-db-secret
                  key: MYSQL_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-db-secret
                  key: MYSQL_PASSWORD
      restartPolicy: Never
  backoffLimit: 3