apiVersion: v1
kind: Service
metadata:
  name: user-db
  namespace: microservices
  labels:
    app: user-db
spec:
  type: ClusterIP
  selector:
    app: user-db
  ports:
  - port: 3306
    targetPort: 3306